### ISSUE TITLE
convert vinyl record to json value directly is supported?

### ISSUE THREAD

**Issue by clojurians-org** [VinylRecords/vinyl-generics#4]
i want to convert a record to J.value directly, it seem don't work...

```haskell
let 
  r = #a =: "aaa" :& b =" "bbb" :& RNil
  j = fromVinyl r :: J.Value
```

**Comment by gagandeepb** [comment]
Hi,

I'm guessing `J.Value` is from Aeson. One way to convert your record `r` to `J.Value` is to use the following:
```haskell
import qualified Generics.SOP                  as S
import qualified GHC.Generics                  as G

data MyPlainRecord = MPR {
  a :: Text,
  b :: Text
} deriving (Show, G.Generic)

instance S.Generic MyPlainRecord
instance S.HasDatatypeInfo MyPlainRecord
instance ToJSON MyPlainRecord
```

The above allows you to do:
```haskell
j :: Value
j = toJSON $ fromVinyl r
```

The other alternative (that does not use `vinyl-generics` in its current form) is to use the instances from this [link](https://github.com/VinylRecords/Vinyl/blob/master/tests/Aeson.hs).

**Comment by clojurians-org** [comment]
thanks.

i don't need the extra record mapping as dynamic behavior from my side.

i use the linked solution [ToJSON instance], 
it say the method 1 has some rare limitation(can't handle Number type..), 
and din't support the FromJSON currently, it's not big deal by the way.

so i'm investigate the general solution and support ToJSON and also FromJSON from various place.

i will also read the json-sop and composite-aeson to make the decison.
and post the conclusion for reference.

**Comment by clojurians-org** [comment]
the methd1 is enough still. the limit is under [NOT encode self-contained JSON values] condition
